### ISSUE TITLE
Error with JHipster 6.8.0

### ISSUE THREAD

**Issue by erickjx** [mshima/generator-jhipster-customizer#35]
Hi,

Today i upgrade to JHipster 6.8.0, and i want test new version with customizer, and have this error, the test work well with 6.7.1: 

```
events.js:288
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property CLIENT_MAIN_SRC_DIR of [object Object] which has only a getter
    at Function.assign (<anonymous>)
    at module.exports.applyPatcher (/usr/local/lib/node_modules/generator-jhipster-customizer/lib/environment.js:108:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:647:25)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:47:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.once.once (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:648:11)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:668:20)
    at processImmediate (internal/timers.js:456:21)
INFO! App: child process exited with code 1
```

**Comment by mshima** [comment]
Should be fixed.
